@echo off
REM Startup script for node: chat-admin-1
REM Generated by topology-configurator

REM Get the directory where this script is located
set SCRIPT_DIR=%~dp0

REM Path to the banyan executable
REM TODO: Set the correct path to banyan binaries
set BANYAN_EXEC=C:\path\to\banyan\win\banyan.exe

REM Check if banyan executable exists
if not exist "%BANYAN_EXEC%" (
    echo Error: banyan executable not found at %BANYAN_EXEC%
    echo Please build the banyan executable or adjust the path in this script
    exit /b 1
)

REM Start the node
echo Starting node: chat-admin-1
"%BANYAN_EXEC%" -privkey="%SCRIPT_DIR%node-identity.pem" -services-dir="%SCRIPT_DIR%services" -listen="/ip4/0.0.0.0/tcp/0" %*
