# Startup script for node: chat-ledger-1
# Generated by topology-configurator

# Get the directory where this script is located
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Path to the banyan executable
# TODO: Set the correct path to banyan binaries
$BanyanExec = "C:\path\to\banyan\win\banyan.exe"

# Check if banyan executable exists
if (-not (Test-Path $BanyanExec)) {
    Write-Host "Error: banyan executable not found at $BanyanExec" -ForegroundColor Red
    Write-Host "Please build the banyan executable or adjust the path in this script" -ForegroundColor Red
    exit 1
}

# Start the node
Write-Host "Starting node: chat-ledger-1" -ForegroundColor Green
$arguments = @(
    "-privkey=`"$ScriptDir\node-identity.pem`"",
    "-services-dir=`"$ScriptDir\services`"",
    "-listen=/ip4/0.0.0.0/tcp/0"
)

# Add any additional arguments passed to this script
$arguments += $args

& $BanyanExec $arguments
