#!/bin/bash
# Startup script for node: chat-static-1
# Generated by topology-configurator

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Path to the banyan executable
# TODO: Set the correct path to banyan binaries
# Detect OS and use appropriate binary
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS - detect architecture
    if [[ $(uname -m) == "arm64" ]]; then
        BANYAN_EXEC="/path/to/banyan/osx/banyan-arm64"
    else
        BANYAN_EXEC="/path/to/banyan/osx/banyan-amd64"
    fi
else
    # Linux
    BANYAN_EXEC="/path/to/banyan/linux/banyan"
fi

# Check if banyan executable exists
if [ ! -f "$BANYAN_EXEC" ]; then
    echo "Error: banyan executable not found at $BANYAN_EXEC"
    echo "Please build the banyan executable or adjust the path in this script"
    exit 1
fi

# Start the node
echo "Starting node: chat-static-1"
"$BANYAN_EXEC" \
    -privkey="${SCRIPT_DIR}/node-identity.pem" \
    -services-dir="${SCRIPT_DIR}/services" \
    -listen="/ip4/0.0.0.0/tcp/0" \
    "$@"
